export interface CarrotlyConfig {
  /** Configuration file version for future compatibility */
  version: string;

  /** When this configuration was created */
  createdAt: string;

  /** CLI version that created this project */
  cliVersion: string;

  /** Project metadata */
  project: {
    name: string;
    description?: string;
    directory: string;
  };

  /** Technical configuration */
  tech: {
    /** API type: GraphQL or REST */
    api: 'rest' | 'graphql';

    /** ORM configuration */
    orm: {
      type: 'mongoose' | 'prisma';
      database?: 'mongodb' | 'postgresql' | 'mysql';
    };

    /** Additional services */
    services: {
      redis: boolean;
      elasticsearch: boolean;
      rabbitmq: boolean;
    };

    /** Development tools */
    tools: {
      codeAssistant: 'cursor' | 'copilot' | 'none';
      docker: boolean;
      testing: boolean;
    };
  };

  /** Generated files and structure tracking */
  generated: {
    /** Timestamp of last generation */
    lastGenerated: string;

    /** Files that were generated by CLI */
    files: string[];

    /** Modules that have been generated */
    modules: GeneratedModule[];
  };
}

export interface GeneratedModule {
  /** Module name */
  name: string;

  /** Module type (e.g., 'resource', 'service', 'controller') */
  type: string;

  /** Files generated for this module */
  files: string[];

  /** When this module was generated */
  createdAt: string;
}

/** Configuration file name */
export const CARROTLY_CONFIG_FILE = '.carrotly.json';

/** Current configuration schema version */
export const CARROTLY_CONFIG_VERSION = '1.0.0';

/** Helper type for creating new configurations */
export interface CreateCarrotlyConfigOptions {
  projectName: string;
  projectDescription?: string;
  directory: string;
  api: 'rest' | 'graphql';
  ormType: 'mongoose' | 'prisma';
  database?: 'mongodb' | 'postgresql' | 'mysql';
  services: string[];
  codeAssistant: 'cursor' | 'copilot' | 'none';
  cliVersion: string;
}
